# https://github.com/docker/build-push-action

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

name: docker

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment for branch
        run:  |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
              echo "TAG=latest" >> $GITHUB_ENV
          else
              echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./inst/Dockerfile
          push: true
          tags: |
            rglab/immunespaceapi:${{ env.TAG }}
            ghcr.io/rglab/immunespaceapi:${{ env.TAG }}
          build-args: |
            BRANCH=${{ env.BRANCH }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
